apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
      - name: api-backend
        image: sanjeevy/api-backend4:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-backend-service
spec:
  selector:
    app: api-backend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
