apiVersion: batch/v1
kind: Job
metadata:
  name: backend-scrapper
spec:
  template:
    spec:
      containers:
        - name: backend
          image: sanjeevy/backend:latest
          imagePullPolicy: Always
          command: ["python3", "/app/scrapper.py"]
          env:
            - name: DB_HOST
              value: cicdrdsdb.cjgiuuuoiuzk.ap-south-1.rds.amazonaws.com
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: password123
            - name: DB_NAME
              value: dbtenders
            - name: DB_PORT
              value: "3306"
      restartPolicy: Never
  backoffLimit: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
