- name: Deploy to Kubernetes
  hosts: k8s
  become: yes
  tasks:
    - name: Copy Kubernetes YAMLs
      copy:
        src: ../k8s/
        dest: /home/ubuntu/k8s/
        mode: '0644'

    - name: Apply Kubernetes deployments
      shell: |
        kubectl apply -f /home/ubuntu/k8s/
