---
- name: Build and Push Docker Images
  hosts: localhost
  become: yes
  tasks:
    - name: Build Backend Docker Image
      community.docker.docker_image:
        name: your-dockerhub-user/backend
        build:
          path: /root/cicdk8/
          dockerfile: Dockerfile.backend
        tag: latest
        push: true
        source: build

    - name: Build Frontend Docker Image
      community.docker.docker_image:
        name: your-dockerhub-user/frontend
        build:
          path: /root/cicdk8/
          dockerfile: Dockerfile.frontend
        tag: latest
        push: true
        source: build

